// scripts/generate-config.js
// Reads src/.env and generates src/emailjs-config.js that exports the EmailJS key.
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', 'src', '.env') });

const outPath = path.join(__dirname, '..', 'src', 'emailjs-config.js');
const key = process.env.Email_JS_KEY || process.env.EMAIL_JS_KEY || process.env.EmailJSKey || process.env.EMAILJS_KEY;
const discordId = process.env.DISCORD_ID || process.env.Discord_Id || process.env.DISCORDID || null;

if (!key) {
  console.error('Email JS key not found in src/.env. Please set Email_JS_KEY=your_key');
  process.exit(1);
}

let content = `// This file is generated by scripts/generate-config.js
// Do NOT commit this file (add to .gitignore). It exposes the client key for bundling.
export const EMAIL_JS_KEY = ${JSON.stringify(key)};
`;

if (discordId) {
  content += `export const DISCORD_ID = ${JSON.stringify(discordId)};\n`;
}

fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('Wrote', outPath);
